trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NodeTool@0
  displayName: 'install node'
  inputs:
    versionSpec: '10.x'

- script: yarn install
  displayName: 'yarn install'

- script: yarn build
  displayName: 'yarn build'

- script: yarn test
  displayName: 'yarn test'

- bash: now deploy --token $(NOW_TOKEN) -A now.development.json
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'dev'))
  displayName: 'now deploy dev'

- bash: now deploy --token $(NOW_TOKEN) -A now.json --prod
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
  displayName: 'now deploy prod'
