trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'install node'

- script: yarn install
  displayName: 'yarn install'

- script: yarn build
  displayName: 'yarn build'

- bash: now deploy -t $(NOW_TOKEN)
  displayName: 'now deploy'
